CREATE TYPE dbo.UsersUdt AS TABLE
(
	UserId BIGINT NULL,
	Email NVARCHAR(150) NOT NULL,
	FirstName NVARCHAR(150),
	LastName NVARCHAR(150),
	Picture VARCHAR(250),
	Sub UNIQUEIDENTIFIER NOT NULL,
	ProviderSub VARCHAR(150),
	ProviderName VARCHAR(50)
)