CREATE TABLE dbo.KLines (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    Symbol VARCHAR(20) NOT NULL,
    Interval VARCHAR,
    TS DATETIME2 NOT NULL,
    OpenPrice DECIMAL(12, 12) NOT NULL,
    HighPrice DECIMAL(12, 12) NOT NULL,
    LowPrice DECIMAL(12, 12) NOT NULL,
    ClosePrice DECIMAL(12, 12) NOT NULL,
    Volume DECIMAL(20, 8) NOT NULL,
    UNIQUE (Symbol, Interval, TS)
);
