CREATE TABLE dbo.Users
(
	UserId BIGINT PRIMARY KEY IDENTITY(1,1),
	Email NVARCHAR(150) UNIQUE NOT NULL,
	FirstName NVARCHAR(150),
	LastName NVARCHAR(150),
	Picture VARCHAR(250),
	ProviderSub VARCHAR(150),
	ProviderName VARCHAR(50),
	CreatedUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
	ModifiedUtc DATETIME2
);
