CREATE TABLE dbo.Users
(
	UserId BIGINT PRIMARY KEY IDENTITY(1,1),
	Username NVARCHAR(150) UNIQUE NOT NULL,
	IsRegistered BIT NOT NULL,
	CreatedUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
	ModifiedUtc DATETIME2
);
